export const Home = () => {
    return (
        <>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>
            <h1>nothing</h1>

        </>
    )
}
